#!/usr/bin/env python

""" SP_CosmCorr - Correct for Cosmic rays
    v1.0: 2018-06-15, mdevogele@lowell.edu
"""

import argparse, shlex

import SP_Toolbox as SP
import numpy as np

from SP_CheckInstrument import CheckInstrument

import SP_diagnostics as diag


from astropy.io import fits

#import cosmic

from astroscrappy import detect_cosmics

from SP_CosmCorr import Cosmic

if __name__ == '__main__':
    
    parser = argparse.ArgumentParser(description='Create a log file')

    parser.add_argument('images', help='images to process or \'all\'',
                        nargs='+')
    
    parser.add_argument('-d',
                        help='Enable or disable the diagnostic',
                        action="store_false",
                        default = True)  

    args = parser.parse_args()
    filenames = args.images    
    Diagnostic = args.d
    
    # call run_the_pipeline only on filenames
    Cosmic(filenames,Diagnostic)
    pass
