#!/usr/bin/env python

""" SP_Prepare2 - Substract background to science data  
    v1.0: 2018-04-19, mdevogele@lowell.edu
  
"""


import argparse, shlex

import os
import logging
import datetime
from astropy.io import ascii
from astropy.io import fits

import SP_Toolbox as toolbox
from SP_CheckObsType import CheckObsType
import _SP_conf
from SP_CheckInstrument import CheckInstrument

from SP_Prepare import Prepare


if __name__ == '__main__':
    
    parser = argparse.ArgumentParser(description='Prepare the files for the spectroscopic pipeline')

    parser.add_argument('-v',
                        help='Increase verbosity',
                        action="store_true")    
    parser.add_argument('images', help='images to process or \'all\'',
                        nargs='+')

    args = parser.parse_args()

    Verbose = args.v
    filenames = args.images  
    
    Prepare(filenames,Verbose)
    pass





