#!/usr/bin/env python

""" SP_TellCorr - Perform the wavelength calibration
    v1.0: 2018-04-20, mdevogele@lowell.edu
"""

import SP_Toolbox as SP
import matplotlib.pyplot as plt
import math
import argparse, shlex
import numpy as np

from SP_CheckInstrument import CheckInstrument
from SP_TellCorr import TellCorr
            
        


if __name__ == '__main__':
    
    parser = argparse.ArgumentParser(description='Extract spectrum')

    parser.add_argument('-d', help='',
                        default = '20171019')
    parser.add_argument('-t',
                        help='Target name',
                        default = False)
    parser.add_argument('-v',
                        help='Increase verbosity',
                        action="store_true")    
    parser.add_argument('-s',
                        help='Standard star spectrum to use',
                        default = 'SpecOut.spec')    
    parser.add_argument('images', help='images to process or \'all\'',
                        nargs='+')
    
    parser.add_argument('-i',
                        help='Instrument')  

    args = parser.parse_args()

    Date = args.d
    Target = args.t
    Verbose = args.v
    Std = args.s
    Instrument = args.i
    filenames = args.images  

    
    TellCorr(filenames,Std,Verbose,Target,Date,Instrument)
    pass